cache:
  directories:
    - ~/.cargo
    - target/debug/.fingerprint
    - target/debug/build
    - target/debug/deps

language: rust

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never

os:
  - linux
  - osx

rust:
  - beta
  - nightly
  - stable

script:
  - cargo build --verbose
  - cargo test --verbose

sudo: false
